//              race state
export const race = {
    isRunning: false,
    totalLaps: 30, 
    winner: null,
};

export const weather = {
    condition: "",
    temperature: "",
    precipitation: 0,
    windSpeed: 0,
};

//              Cars data
export const cars = [
    {
        name: "player",
        color: "blue",
        fuel: 100,
        tyreCompound: "medium",
        tyreLife: 100,
        position: 0, 
        speed: 2,
        strategy: "baseline",
        lapsCompleted: 0,
        fuelServiceRequested: false,
        fuelServiced: false,
        tyreServiceRequested: false,
        tyreServiced: false,
        pitRequested: false,
        isPitting: false,
        newTyreSet: "",
        isDNF: false,
        dnfReason: "",
    },
    {
        name: "computer1",
        color: "red",
        fuel: 100,
        tyreCompound: "medium",
        tyreLife: 100,
        position: 0, 
        speed: 2,
        strategy: "baseline",
        lapsCompleted: 0,
        fuelServiceRequested: false,
        fuelServiced: false,
        tyreServiceRequested: false,
        tyreServiced: false,
        pitRequested: false,
        isPitting: false,
        newTyreSet: "",
        isDNF: false,
        dnfReason: "",
    },
    {
        name: "computer2",
        color: "yellow",
        fuel: 100,
        tyreCompound: "medium",
        tyreLife: 100,
        position: 0, 
        speed: 2,
        strategy: "baseline",
        lapsCompleted: 0,
        fuelServiceRequested: false,
        fuelServiced: false,
        tyreServiceRequested: false,
        tyreServiced: false,
        pitRequested: false,
        isPitting: false,
        newTyreSet: "",
        isDNF: false,
        dnfReason: "",
    },
    {
        name: "computer3",
        color: "violet",
        fuel: 100,
        tyreCompound: "medium",
        tyreLife: 100,
        position: 0, 
        speed: 2,
        strategy: "baseline",
        lapsCompleted: 0,
        fuelServiceRequested: false,
        fuelServiced: false,
        tyreServiceRequested: false,
        tyreServiced: false,
        pitRequested: false,
        isPitting: false,
        newTyreSet: "",
        isDNF: false,
        dnfReason: "",
    },
];

export const docFuelWarning = {
    computer1: false,
    computer2: false,
    computer3: false,
};

export const docTyreWarning = {
    computer1: false,
    computer2: false,
    computer3: false,
};
